name: Java Release CI

on: [release]

jobs:
  build:
    runs-on: ubuntu-latest

  permissions:
    contents: read
    packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Build without tests
        run: mvn -DskipTests package
      - name: Build with tests
        run: mvn --batch-mode --update-snapshots verify
      - name: Package Java Project as JAR
        run: mvn package
      - name: Publish JAR to Packages page
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN:  ${{ secrets.MY_WAY_ICS }}