name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        runs:
        using: "composite"
        steps:
           - run: mvn --batch-mode --update-snapshots package
           - run: mvn --batch-mode --file pom.xml
           - run: mvn --batch-mode --update-snapshots verify
