name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Build without tests
        run: mvn -DskipTests package
      - name: Jacoco
        run: mvn clean verify
      - name: Archive Jacoco reports
        uses: actions/upload-artifact@v3
        with:
            name: jacoco-reports
            path: target/site/jacoco
      - name: Build with tests
        run: mvn --batch-mode --update-snapshots verify